name: Mon premier WorkFlow
on: workflow_dispatch
jobs:
  premierJob:
    runs-on: ubuntu-latest
    steps:
      - name: Mon premier job
        run: echo "Démarrage du job"
      - name: Mes premieres instructions
        run: ls /
      - name: Fin du premier job
        run: echo "That's all folks!"

# workflow_dispatch indique que le workflow pourra être déclanché manuellement depuis GitHub